  
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java application"
      - cd CustomerService
      - mvn -DskipTests clean package
      - docker build -t ij025-pod1-customer-ms-registry:latest .
      - docker tag ij025-pod1-customer-ms-registry:latest 941516478045.dkr.ecr.ap-northeast-1.amazonaws.com/ij025-pod1-customer-ms-registry:latest

  post_build:
    commands:
      - echo "Post_build"
      - docker push 941516478045.dkr.ecr.ap-northeast-1.amazonaws.com/ij025-pod1-customer-ms-registry:latest
      - printf '[{"name":"customer-ms-container","imageUri":"%s"}]' 941516478045.dkr.ecr.ap-northeast-1.amazonaws.com//ij025-pod1-customer-ms-registry:latest > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
      - CustomerService/taskdefinition.json